import fs from 'fs';
import path from 'path';

const datasetPath = "C:\\Nationwide Sites\\US Cities Dataset folder\\us_cities dataset.json";
const outputPath = path.join(process.cwd(), 'data', 'states.js');

const stateNames = {
  "AL": "Alabama", "AK": "Alaska", "AZ": "Arizona", "AR": "Arkansas", "CA": "California",
  "CO": "Colorado", "CT": "Connecticut", "DE": "Delaware", "FL": "Florida", "GA": "Georgia",
  "HI": "Hawaii", "ID": "Idaho", "IL": "Illinois", "IN": "Indiana", "IA": "Iowa",
  "KS": "Kansas", "KY": "Kentucky", "LA": "Louisiana", "ME": "Maine", "MD": "Maryland",
  "MA": "Massachusetts", "MI": "Michigan", "MN": "Minnesota", "MS": "Mississippi", "MO": "Missouri",
  "MT": "Montana", "NE": "Nebraska", "NV": "Nevada", "NH": "New Hampshire", "NJ": "New Jersey",
  "NM": "New Mexico", "NY": "New York", "NC": "North Carolina", "ND": "North Dakota", "OH": "Ohio",
  "OK": "Oklahoma", "OR": "Oregon", "PA": "Pennsylvania", "RI": "Rhode Island", "SC": "South Carolina",
  "SD": "South Dakota", "TN": "Tennessee", "TX": "Texas", "UT": "Utah", "VT": "Vermont",
  "VA": "Virginia", "WA": "Washington", "WV": "West Virginia", "WI": "Wisconsin", "WY": "Wyoming"
};

function slugify(text) {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)+/g, '');
}

console.log("Reading dataset from: " + datasetPath);
const rawData = fs.readFileSync(datasetPath, 'utf8');
const allCities = JSON.parse(rawData);

const statesMap = {};

for (const city of allCities) {
  const abbr = city.state;
  if (!stateNames[abbr]) continue; // Skip if not a valid US state (e.g. PR, DC)
  
  if (!statesMap[abbr]) {
    statesMap[abbr] = {
      slug: slugify(stateNames[abbr]),
      name: stateNames[abbr],
      abbr: abbr,
      cities: []
    };
  }
  
  const zipCodes = city.zip_codes || [];
  
  statesMap[abbr].cities.push({
    name: city.city,
    slug: slugify(city.city),
    county: city.county,
    zip: zipCodes.length > 0 ? zipCodes[0] : "",
    zipCodes: zipCodes
  });
}

const statesArray = Object.values(statesMap).sort((a, b) => a.name.localeCompare(b.name));

for (const state of statesArray) {
  state.cities.sort((a, b) => a.name.localeCompare(b.name));
}

const fileContent = `// AUTO-GENERATED by scripts/processDataset.js
const states = ${JSON.stringify(statesArray, null, 2)};
export default states;
`;

fs.writeFileSync(outputPath, fileContent);
console.log(`Successfully generated ${statesArray.length} states in ${outputPath}`);
