import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

async function run() {
  const { default: states } = await import('../data/states.js');
  console.log(`Original states count: ${states.length}`);
  
  const filteredStates = states.filter(s => s.slug !== 'alaska' && s.slug !== 'hawaii');
  console.log(`Filtered states count: ${filteredStates.length}`);
  
  const content = `// AUTO-GENERATED by scripts/processDataset.js — do not edit manually
// Source: us_cities dataset.json
const states = ${JSON.stringify(filteredStates, null, 2)};
export default states;
`;

  const outputPath = path.resolve(__dirname, '../data/states.js');
  fs.writeFileSync(outputPath, content);
  console.log('Successfully updated data/states.js');
}

run();
